shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart-detail'),
    path('add/<int:product_id>', views.cart_add, name='cart-add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart-remove'),
]

shop/myshop/urls.py
from django.urls import path
from . import views


app_name = 'myshop'


urlpatterns = [
    path('', views.product_list, name='product-list'),
    path('<int:category_id>/', views.product_list, name='product-list-by-category'),
    path('product/<int:product_id>', views.product_detail, name='product-detail')
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order-create'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('cart', include('cart.urls', namespace='cart')),
    path('orders', include('orders.urls', namespace='orders')),
    path('', include('myshop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/myshop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return f"{self.name}"
    

    def get_absolute_url(self):
        return reverse("myshop:product-list-by-category", args=[self.id])
    


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    count = models.PositiveIntegerField()
    image = models.ImageField(default='product-images/default.jpg')

    def __str__(self) -> str:
        return f"{self.name}"
    
    def get_absolute_url(self):
        return reverse("myshop:product-detail", args=[self.id])
    

shop/orders/models.py
from django.db import models
from myshop.models import Product

class Order(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self) -> str:
        return f"Заказ {self.id}"
    

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)


    def __str__(self) -> str:
        return f"{self.id}"
    
    def get_cost(self):
        return self.price * self.quantity
    
    

shop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form): 
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int) 
    add = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'email', 'address', 'city']

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], add=cd['add'])
    return redirect('cart:cart-detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart-detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'add': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

shop/myshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from cart.forms import CartAddProductForm


def product_list(request, category_id=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(count__gt=0)
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        products = products.filter(category=category)

    return render(request, 'myshop/products_list.html', 
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  }
                  )

#myshop/product_detail.html

def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id, count__gt=0)
    cart_product_form = CartAddProductForm()
    return render(request, 'myshop/product_detail.html', {'product': product,
                                                          'cart_product_form': cart_product_form,
                                                          })

shop/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)
    print('fhfh')
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                    )
            cart.clear()
            return render(request, 'orders/order_created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order_create.html', {'cart': cart, 'form': form}
)

shop/cart/templates/cart/cart_detail.html
{% extends "myshop/base.html" %} {% load static %}
{% block title %} Your shopping cart
{% endblock %}
{% block content %}
<h1>Your shopping cart</h1> <table class="cart">
<thead>
    <tr>
        <th>Фото</th> <th>Товар</th> <th>Количество</th> <th>Удалить</th> <th>Цена за штуку</th> <th>Цена</th>
        </tr> </thead> <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr> <td>
        <a href="{{ product.get_absolute_url }}">
        <img src="{% if product.image %}{{ product.image.url }} {% else %}{% static "img/no_image.png" %}{% endif %}">
        </a> </td>
        <td>{{ product.name }}</td> 
        <td><form action="{% url "cart:cart-add" product.id %}" method="post"> {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.override }}
            <input type="submit" value="Обновить">
            {% csrf_token %}
            </form>
        </td> 
        <td>
        <form action="{% url "cart:cart-remove" product.id %}" method="post">
        <input type="submit" value="Удалить">
        {% csrf_token %}
        </form> </td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td> </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
        <td>Итого</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
        </tr> </tbody>
        </table>
        <p class="text-right">
        <a href="{% url "shop:product-list" %}" class="button light">Продолжить покупки</a>
        <a href="{% url "orders:order-create" %}" class="button">Купить</a>
        </p>
        {% endblock %}

shop/myshop/templates/myshop/base.html
{% load static %} 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}RX Shop{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <a href="/" class="logo">RX Shop</a>
        </div>
        <div id="subheader">
            <div class="cart">{% with total_items=cart|length %}
                {% if total_items > 0 %}
                Ваша корзина:
                <a href="{% url "cart:cart-detail" %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
                </a>
                {% else %}
                В корзине нет товаров
                {% endif %} {% endwith %}</div>
        </div>
        <div id="content">
            {% block content %} {% endblock %}
        </div>
    </body>
</html>

shop/myshop/templates/myshop/product_detail.html
{% extends "myshop/base.html" %} {% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %} {% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
    <a href="{{ product.category.get_absolute_url }}"> {{ product.category }}</a>
    </h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url "cart:cart-add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
        </form>
    {{ product.description|linebreaks }}
</div>
{% endblock %}

shop/myshop/templates/myshop/products_list.html
{% extends "myshop/base.html" %} {% load static %}
{% block title %}
{% if category %}{{ category.name }}
{% else %}Products
{% endif %}
{% endblock %}
{% block content %} 

<div id="sidebar">
    <h3>Категории</h3> 
    <ul>
        <li {% if not category %}class="selected"{% endif %}> <a href="{% url "myshop:product-list" %}">All</a>
        </li>
        {% for c in categories %}
            <li {% if category.id == c.id %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a> </li>
        {% endfor %}
    </ul>
</div>

<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Товары {% endif %}</h1>
    {% for product in products %}
        <div class="item">
        <a href="{{ product.get_absolute_url }}">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a> <br>
        ${{ product.price }}
        </div>
    {% endfor %}
</div>
{% endblock %}

shop/orders/templates/orders/order_create.html
{% extends "myshop/base.html" %}
{% block title %} Checkout
{% endblock %}
{% block content %} 
<h1>Оформление заказа</h1>
<div class="order-info">
    <h3>Ваш заказ</h3> 
        <ul>
        {% for item in cart %}
            <li>
            {{ item.quantity }}x {{ item.product.name }}
            <span>${{ item.total_price }}</span> 
            </li>
        {% endfor %}
        </ul>
    <p>Итого: ${{ cart.get_total_price }}</p> </div>
    <form method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Оформить"></p> 
    {% csrf_token %}
    </form>
{% endblock %}

shop/orders/templates/orders/order_created.html
{% extends "myshop/base.html" %}
{% block title %} 
Thank you
{% endblock %}
{% block content %}
<h1>Спасибо!</h1>
<p>Ваш заказ успешно оформлен. Номер вашего заказа <strong>{{ order.id }}</strong>.</p>
{% endblock %}